# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/inexact-struct-dsl-compiler/all/inexact-struct-dsl-compiler.rbi
#
# inexact-struct-dsl-compiler-0.0.1

module Tapioca
end
module Tapioca::Compilers
end
class Tapioca::Compilers::InexactStruct < Tapioca::Dsl::Compiler
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
module Tapioca::Compilers::InexactStruct::ConstantType
end
