# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/netrc/all/netrc.rbi
#
# netrc-0.11.0

class Netrc
end
class Netrc::TokenArray < Array
end
class Netrc::Error < StandardError
end
