# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/prism/all/prism.rbi
#
# prism-0.27.0

module Prism
end
class Prism::Node
end
class Prism::AliasGlobalVariableNode < Prism::Node
end
class Prism::AliasMethodNode < Prism::Node
end
class Prism::AlternationPatternNode < Prism::Node
end
class Prism::AndNode < Prism::Node
end
class Prism::ArgumentsNode < Prism::Node
end
class Prism::ArrayNode < Prism::Node
end
class Prism::ArrayPatternNode < Prism::Node
end
class Prism::AssocNode < Prism::Node
end
class Prism::AssocSplatNode < Prism::Node
end
class Prism::BackReferenceReadNode < Prism::Node
end
class Prism::BeginNode < Prism::Node
end
class Prism::BlockArgumentNode < Prism::Node
end
class Prism::BlockLocalVariableNode < Prism::Node
end
class Prism::BlockNode < Prism::Node
end
class Prism::BlockParameterNode < Prism::Node
end
class Prism::BlockParametersNode < Prism::Node
end
class Prism::BreakNode < Prism::Node
end
class Prism::CallAndWriteNode < Prism::Node
end
class Prism::CallNode < Prism::Node
end
class Prism::CallOperatorWriteNode < Prism::Node
end
class Prism::CallOrWriteNode < Prism::Node
end
class Prism::CallTargetNode < Prism::Node
end
class Prism::CapturePatternNode < Prism::Node
end
class Prism::CaseMatchNode < Prism::Node
end
class Prism::CaseNode < Prism::Node
end
class Prism::ClassNode < Prism::Node
end
class Prism::ClassVariableAndWriteNode < Prism::Node
end
class Prism::ClassVariableOperatorWriteNode < Prism::Node
end
class Prism::ClassVariableOrWriteNode < Prism::Node
end
class Prism::ClassVariableReadNode < Prism::Node
end
class Prism::ClassVariableTargetNode < Prism::Node
end
class Prism::ClassVariableWriteNode < Prism::Node
end
class Prism::ConstantAndWriteNode < Prism::Node
end
class Prism::ConstantOperatorWriteNode < Prism::Node
end
class Prism::ConstantOrWriteNode < Prism::Node
end
class Prism::ConstantPathAndWriteNode < Prism::Node
end
class Prism::ConstantPathNode < Prism::Node
end
class Prism::ConstantPathOperatorWriteNode < Prism::Node
end
class Prism::ConstantPathOrWriteNode < Prism::Node
end
class Prism::ConstantPathTargetNode < Prism::Node
end
class Prism::ConstantPathWriteNode < Prism::Node
end
class Prism::ConstantReadNode < Prism::Node
end
class Prism::ConstantTargetNode < Prism::Node
end
class Prism::ConstantWriteNode < Prism::Node
end
class Prism::DefNode < Prism::Node
end
class Prism::DefinedNode < Prism::Node
end
class Prism::ElseNode < Prism::Node
end
class Prism::EmbeddedStatementsNode < Prism::Node
end
class Prism::EmbeddedVariableNode < Prism::Node
end
class Prism::EnsureNode < Prism::Node
end
class Prism::FalseNode < Prism::Node
end
class Prism::FindPatternNode < Prism::Node
end
class Prism::FlipFlopNode < Prism::Node
end
class Prism::FloatNode < Prism::Node
end
class Prism::ForNode < Prism::Node
end
class Prism::ForwardingArgumentsNode < Prism::Node
end
class Prism::ForwardingParameterNode < Prism::Node
end
class Prism::ForwardingSuperNode < Prism::Node
end
class Prism::GlobalVariableAndWriteNode < Prism::Node
end
class Prism::GlobalVariableOperatorWriteNode < Prism::Node
end
class Prism::GlobalVariableOrWriteNode < Prism::Node
end
class Prism::GlobalVariableReadNode < Prism::Node
end
class Prism::GlobalVariableTargetNode < Prism::Node
end
class Prism::GlobalVariableWriteNode < Prism::Node
end
class Prism::HashNode < Prism::Node
end
class Prism::HashPatternNode < Prism::Node
end
class Prism::IfNode < Prism::Node
end
class Prism::ImaginaryNode < Prism::Node
end
class Prism::ImplicitNode < Prism::Node
end
class Prism::ImplicitRestNode < Prism::Node
end
class Prism::InNode < Prism::Node
end
class Prism::IndexAndWriteNode < Prism::Node
end
class Prism::IndexOperatorWriteNode < Prism::Node
end
class Prism::IndexOrWriteNode < Prism::Node
end
class Prism::IndexTargetNode < Prism::Node
end
class Prism::InstanceVariableAndWriteNode < Prism::Node
end
class Prism::InstanceVariableOperatorWriteNode < Prism::Node
end
class Prism::InstanceVariableOrWriteNode < Prism::Node
end
class Prism::InstanceVariableReadNode < Prism::Node
end
class Prism::InstanceVariableTargetNode < Prism::Node
end
class Prism::InstanceVariableWriteNode < Prism::Node
end
class Prism::IntegerNode < Prism::Node
end
class Prism::InterpolatedMatchLastLineNode < Prism::Node
  include Prism::RegularExpressionOptions
end
class Prism::InterpolatedRegularExpressionNode < Prism::Node
  include Prism::RegularExpressionOptions
end
class Prism::InterpolatedStringNode < Prism::Node
  include Prism::HeredocQuery
end
class Prism::InterpolatedSymbolNode < Prism::Node
end
class Prism::InterpolatedXStringNode < Prism::Node
  include Prism::HeredocQuery
end
class Prism::ItParametersNode < Prism::Node
end
class Prism::KeywordHashNode < Prism::Node
end
class Prism::KeywordRestParameterNode < Prism::Node
end
class Prism::LambdaNode < Prism::Node
end
class Prism::LocalVariableAndWriteNode < Prism::Node
end
class Prism::LocalVariableOperatorWriteNode < Prism::Node
end
class Prism::LocalVariableOrWriteNode < Prism::Node
end
class Prism::LocalVariableReadNode < Prism::Node
end
class Prism::LocalVariableTargetNode < Prism::Node
end
class Prism::LocalVariableWriteNode < Prism::Node
end
class Prism::MatchLastLineNode < Prism::Node
  include Prism::RegularExpressionOptions
end
class Prism::MatchPredicateNode < Prism::Node
end
class Prism::MatchRequiredNode < Prism::Node
end
class Prism::MatchWriteNode < Prism::Node
end
class Prism::MissingNode < Prism::Node
end
class Prism::ModuleNode < Prism::Node
end
class Prism::MultiTargetNode < Prism::Node
end
class Prism::MultiWriteNode < Prism::Node
end
class Prism::NextNode < Prism::Node
end
class Prism::NilNode < Prism::Node
end
class Prism::NoKeywordsParameterNode < Prism::Node
end
class Prism::NumberedParametersNode < Prism::Node
end
class Prism::NumberedReferenceReadNode < Prism::Node
end
class Prism::OptionalKeywordParameterNode < Prism::Node
end
class Prism::OptionalParameterNode < Prism::Node
end
class Prism::OrNode < Prism::Node
end
class Prism::ParametersNode < Prism::Node
end
class Prism::ParenthesesNode < Prism::Node
end
class Prism::PinnedExpressionNode < Prism::Node
end
class Prism::PinnedVariableNode < Prism::Node
end
class Prism::PostExecutionNode < Prism::Node
end
class Prism::PreExecutionNode < Prism::Node
end
class Prism::ProgramNode < Prism::Node
end
class Prism::RangeNode < Prism::Node
end
class Prism::RationalNode < Prism::Node
end
class Prism::RedoNode < Prism::Node
end
class Prism::RegularExpressionNode < Prism::Node
  include Prism::RegularExpressionOptions
end
class Prism::RequiredKeywordParameterNode < Prism::Node
end
class Prism::RequiredParameterNode < Prism::Node
end
class Prism::RescueModifierNode < Prism::Node
end
class Prism::RescueNode < Prism::Node
end
class Prism::RestParameterNode < Prism::Node
end
class Prism::RetryNode < Prism::Node
end
class Prism::ReturnNode < Prism::Node
end
class Prism::SelfNode < Prism::Node
end
class Prism::ShareableConstantNode < Prism::Node
end
class Prism::SingletonClassNode < Prism::Node
end
class Prism::SourceEncodingNode < Prism::Node
end
class Prism::SourceFileNode < Prism::Node
end
class Prism::SourceLineNode < Prism::Node
end
class Prism::SplatNode < Prism::Node
end
class Prism::StatementsNode < Prism::Node
end
class Prism::StringNode < Prism::Node
  include Prism::HeredocQuery
end
class Prism::SuperNode < Prism::Node
end
class Prism::SymbolNode < Prism::Node
end
class Prism::TrueNode < Prism::Node
end
class Prism::UndefNode < Prism::Node
end
class Prism::UnlessNode < Prism::Node
end
class Prism::UntilNode < Prism::Node
end
class Prism::WhenNode < Prism::Node
end
class Prism::WhileNode < Prism::Node
end
class Prism::XStringNode < Prism::Node
  include Prism::HeredocQuery
end
class Prism::YieldNode < Prism::Node
end
module Prism::ArgumentsNodeFlags
end
module Prism::ArrayNodeFlags
end
module Prism::CallNodeFlags
end
module Prism::EncodingFlags
end
module Prism::IntegerBaseFlags
end
module Prism::InterpolatedStringNodeFlags
end
module Prism::KeywordHashNodeFlags
end
module Prism::LoopFlags
end
module Prism::ParameterFlags
end
module Prism::RangeFlags
end
module Prism::RegularExpressionFlags
end
module Prism::ShareableConstantNodeFlags
end
module Prism::StringFlags
end
module Prism::SymbolFlags
end
module Prism::RegularExpressionOptions
end
module Prism::HeredocQuery
end
class Prism::ConstantPathNode::DynamicPartsInConstantPathError < StandardError
end
class Prism::ConstantPathNode::MissingNodesInConstantPathError < StandardError
end
class Prism::Source
end
class Prism::Location
end
class Prism::Comment
end
class Prism::InlineComment < Prism::Comment
end
class Prism::EmbDocComment < Prism::Comment
end
class Prism::MagicComment
end
class Prism::ParseError
end
class Prism::ParseWarning
end
class Prism::Result
end
class Prism::ParseResult < Prism::Result
end
class Prism::LexResult < Prism::Result
end
class Prism::ParseLexResult < Prism::Result
end
class Prism::Token
end
class Prism::ParseResult::Comments
end
class Prism::ParseResult::Comments::NodeTarget
end
class Prism::ParseResult::Comments::LocationTarget
end
class Prism::BasicVisitor
end
class Prism::Visitor < Prism::BasicVisitor
end
class Prism::ParseResult::Newlines < Prism::Visitor
end
module Prism::Debug
end
class Prism::Debug::ISeq
end
class Prism::Debug::Encoding
end
module Prism::Pack
end
class Prism::Pack::Directive
end
class Prism::Pack::Format
end
