# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/psych/all/psych.rbi
#
# psych-5.2.0

module Psych
end
class Psych::Exception < RuntimeError
end
class Psych::BadAlias < Psych::Exception
end
class Psych::AliasesNotEnabled < Psych::BadAlias
end
class Psych::AnchorNotDefined < Psych::BadAlias
end
class Psych::DisallowedClass < Psych::Exception
end
class Psych::SyntaxError < Psych::Exception
end
class Psych::Omap < Hash
end
class Psych::Set < Hash
end
class Psych::ClassLoader
end
class Psych::ClassLoader::Restricted < Psych::ClassLoader
end
class Psych::ScalarScanner
end
module Psych::Nodes
end
class Psych::Nodes::Node
  include Enumerable
end
class Psych::Nodes::Stream < Psych::Nodes::Node
end
class Psych::Nodes::Document < Psych::Nodes::Node
end
class Psych::Nodes::Sequence < Psych::Nodes::Node
end
class Psych::Nodes::Scalar < Psych::Nodes::Node
end
class Psych::Nodes::Mapping < Psych::Nodes::Node
end
class Psych::Nodes::Alias < Psych::Nodes::Node
end
module Psych::Streaming
end
module Psych::Streaming::ClassMethods
end
module Psych::Visitors
end
class Psych::Visitors::Visitor
end
class Psych::Visitors::ToRuby < Psych::Visitors::Visitor
end
class Psych::Visitors::NoAliasRuby < Psych::Visitors::ToRuby
end
class Psych::Visitors::Emitter < Psych::Visitors::Visitor
end
class Psych::Handler
end
class Psych::Handler::DumperOptions
end
class Psych::TreeBuilder < Psych::Handler
end
class Psych::Visitors::YAMLTree < Psych::Visitors::Visitor
end
class Psych::Visitors::YAMLTree::Registrar
end
class Psych::Visitors::RestrictedYAMLTree < Psych::Visitors::YAMLTree
end
module Psych::JSON
end
module Psych::JSON::RubyEvents
end
class Psych::Visitors::JSONTree < Psych::Visitors::YAMLTree
  include Psych::JSON::RubyEvents
end
class Psych::Visitors::DepthFirst < Psych::Visitors::Visitor
end
class Psych::Parser
end
class Psych::Parser::Mark < Anonymous_Struct_9
end
class Psych::Coder
end
module Kernel
end
class Object < BasicObject
end
class Psych::Stream < Psych::Visitors::YAMLTree
  extend Psych::Streaming::ClassMethods
  include Psych::Streaming
end
class Psych::Stream::Emitter < Psych::Emitter
end
module Psych::JSON::YAMLEvents
end
class Psych::JSON::TreeBuilder < Psych::TreeBuilder
  include Psych::JSON::YAMLEvents
end
class Psych::JSON::Stream < Psych::Visitors::JSONTree
  extend Psych::Streaming::ClassMethods
  include Psych::JSON::RubyEvents
  include Psych::Streaming
end
class Psych::JSON::Stream::Emitter < Psych::Stream::Emitter
  include Psych::JSON::YAMLEvents
end
module Psych::Handlers
end
class Psych::Handlers::DocumentStream < Psych::TreeBuilder
end
class InvalidName___Class_0x00___Config_10
end
