# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/racc/all/racc.rbi
#
# racc-1.8.1

module Racc
end
class Racc::ParseError < StandardError
end
class Racc::Parser
end
