# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: false
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rbi/all/rbi.rbi
#
# rbi-0.1.12

module RBI
end
class RBI::Loc
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class RBI::Node
  extend T::Helpers
  extend T::Private::Abstract::Hooks
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  extend T::Sig
  extend T::Sig
  extend T::Sig
end
class RBI::Comment < RBI::Node
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  extend T::Sig
end
class RBI::BlankLine < RBI::Comment
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  extend T::Sig
end
class RBI::NodeWithComments < RBI::Node
  extend T::Helpers
  extend T::Private::Abstract::Hooks
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  extend T::Sig
  extend T::Sig
end
class RBI::Tree < RBI::NodeWithComments
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  extend T::Sig
  extend T::Sig
  extend T::Sig
  extend T::Sig
  extend T::Sig
  extend T::Sig
  extend T::Sig
  extend T::Sig
  extend T::Sig
  extend T::Sig
  extend T::Sig
end
class RBI::File
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  extend T::Sig
end
class RBI::Scope < RBI::Tree
  extend T::Helpers
  extend T::Private::Abstract::Hooks
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  extend T::Sig
  extend T::Sig
  include RBI::Indexable
end
class RBI::Module < RBI::Scope
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  extend T::Sig
  extend T::Sig
end
class RBI::Class < RBI::Scope
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  extend T::Sig
  extend T::Sig
end
class RBI::SingletonClass < RBI::Scope
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  extend T::Sig
end
class RBI::Struct < RBI::Scope
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  extend T::Sig
  extend T::Sig
end
class RBI::Const < RBI::NodeWithComments
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  extend T::Sig
  extend T::Sig
  extend T::Sig
  include RBI::Indexable
end
class RBI::Attr < RBI::NodeWithComments
  extend T::Helpers
  extend T::Private::Abstract::Hooks
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  extend T::Sig
  extend T::Sig
  extend T::Sig
  include RBI::Indexable
end
class RBI::AttrAccessor < RBI::Attr
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  extend T::Sig
end
class RBI::AttrReader < RBI::Attr
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  extend T::Sig
end
class RBI::AttrWriter < RBI::Attr
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  extend T::Sig
end
class RBI::Method < RBI::NodeWithComments
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  extend T::Sig
  extend T::Sig
  extend T::Sig
  include RBI::Indexable
end
class RBI::Param < RBI::NodeWithComments
  extend T::Helpers
  extend T::Private::Abstract::Hooks
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  extend T::Sig
end
class RBI::ReqParam < RBI::Param
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class RBI::OptParam < RBI::Param
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  extend T::Sig
end
class RBI::RestParam < RBI::Param
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  extend T::Sig
end
class RBI::KwParam < RBI::Param
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  extend T::Sig
end
class RBI::KwOptParam < RBI::Param
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  extend T::Sig
end
class RBI::KwRestParam < RBI::Param
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  extend T::Sig
end
class RBI::BlockParam < RBI::Param
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  extend T::Sig
end
class RBI::Mixin < RBI::NodeWithComments
  extend T::Helpers
  extend T::Private::Abstract::Hooks
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  extend T::Sig
  extend T::Sig
end
class RBI::Include < RBI::Mixin
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  extend T::Sig
  extend T::Sig
  include RBI::Indexable
end
class RBI::Extend < RBI::Mixin
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  extend T::Sig
  extend T::Sig
  include RBI::Indexable
end
class RBI::Visibility < RBI::NodeWithComments
  extend T::Helpers
  extend T::Private::Abstract::Hooks
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  extend T::Sig
end
class RBI::Public < RBI::Visibility
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class RBI::Protected < RBI::Visibility
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class RBI::Private < RBI::Visibility
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class RBI::Send < RBI::NodeWithComments
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  extend T::Sig
  extend T::Sig
  extend T::Sig
  include RBI::Indexable
end
class RBI::Arg < RBI::Node
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  extend T::Sig
end
class RBI::KwArg < RBI::Arg
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  extend T::Sig
end
class RBI::Sig < RBI::Node
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  extend T::Sig
end
class RBI::SigParam < RBI::NodeWithComments
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  extend T::Sig
end
class RBI::TStruct < RBI::Class
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class RBI::TStructField < RBI::NodeWithComments
  extend T::Helpers
  extend T::Private::Abstract::Hooks
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  extend T::Sig
  extend T::Sig
end
class RBI::TStructConst < RBI::TStructField
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  extend T::Sig
  extend T::Sig
  include RBI::Indexable
end
class RBI::TStructProp < RBI::TStructField
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  extend T::Sig
  extend T::Sig
  include RBI::Indexable
end
class RBI::TEnum < RBI::Class
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class RBI::TEnumBlock < RBI::NodeWithComments
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  extend T::Sig
  extend T::Sig
  extend T::Sig
  include RBI::Indexable
end
class RBI::Helper < RBI::NodeWithComments
  extend T::Helpers
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  extend T::Sig
  extend T::Sig
  include RBI::Indexable
end
class RBI::TypeMember < RBI::NodeWithComments
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  extend T::Sig
  extend T::Sig
  include RBI::Indexable
end
class RBI::MixesInClassMethods < RBI::Mixin
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  extend T::Sig
  extend T::Sig
  include RBI::Indexable
end
class RBI::RequiresAncestor < RBI::NodeWithComments
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  extend T::Sig
  extend T::Sig
  include RBI::Indexable
end
class RBI::Visitor
  extend T::Helpers
  extend T::Private::Abstract::Hooks
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class RBI::Index < RBI::Visitor
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  include T::Enumerable
end
module RBI::Indexable
  extend T::Helpers
  extend T::Private::Abstract::Hooks
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
module RBI::Rewriters
end
class RBI::Rewriters::AddSigTemplates < RBI::Visitor
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class RBI::Rewriters::Annotate < RBI::Visitor
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class RBI::Rewriters::Deannotate < RBI::Visitor
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class RBI::Rewriters::FilterVersions < RBI::Visitor
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class RBI::Rewriters::Merge
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class RBI::Rewriters::Merge::Keep < T::Enum
end
class RBI::Rewriters::Merge::Conflict < T::Struct
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Props::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Serializable::ClassMethods
  extend T::Sig
end
class RBI::Rewriters::Merge::TreeMerger < RBI::Visitor
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class RBI::Rewriters::Merge::ConflictTreeMerger < RBI::Visitor
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
end
class RBI::MergeTree < RBI::Tree
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class RBI::ConflictTree < RBI::Tree
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class RBI::ScopeConflict < RBI::Tree
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class RBI::Rewriters::NestSingletonMethods < RBI::Visitor
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class RBI::Rewriters::NestNonPublicMethods < RBI::Visitor
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class RBI::VisibilityGroup < RBI::Tree
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  extend T::Sig
end
class RBI::Rewriters::GroupNodes < RBI::Visitor
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class RBI::Group < RBI::Tree
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  extend T::Sig
end
class RBI::Group::Kind < T::Enum
end
class RBI::Rewriters::RemoveKnownDefinitions < RBI::Visitor
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class RBI::Rewriters::RemoveKnownDefinitions::Operation < T::Struct
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Props::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Serializable::ClassMethods
  extend T::Sig
end
class RBI::Rewriters::SortNodes < RBI::Visitor
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class RBI::ParseError < StandardError
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class RBI::UnexpectedParserError < StandardError
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class RBI::Parser
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class RBI::Parser::Visitor < Prism::Visitor
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class RBI::Parser::TreeBuilder < RBI::Parser::Visitor
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class RBI::Parser::SigBuilder < RBI::Parser::Visitor
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class RBI::Printer < RBI::Visitor
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class RBI::Formatter
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
