# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: false
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/tapioca/all/tapioca.rbi
#
# tapioca-0.13.3

module Tapioca
  extend T::Sig
end
class Tapioca::Error < StandardError
end
module Tapioca::Runtime
end
module Tapioca::Runtime::AttachedClassOf
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
module Tapioca::Runtime::Reflection
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  extend Tapioca::Runtime::Reflection
  include Tapioca::Runtime::AttachedClassOf
end
module Tapioca::Runtime::Reflection::UNDEFINED_CONSTANT
end
module Tapioca::Runtime::Trackers
  extend T::Sig
end
module Tapioca::Runtime::Trackers::Tracker
  extend T::Helpers
  extend T::Private::Abstract::Hooks
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
module Tapioca::Runtime::Trackers::Mixin
  extend T::Sig
  extend Tapioca::Runtime::Trackers::Tracker
end
class Tapioca::Runtime::Trackers::Mixin::Type < T::Enum
end
class Module
end
module Tapioca::Runtime::Trackers::ConstantDefinition
  extend T::Sig
  extend Tapioca::Runtime::Reflection
  extend Tapioca::Runtime::Trackers::Tracker
end
class Tapioca::Runtime::Trackers::ConstantDefinition::ConstantLocation < T::Struct
  extend T::Props::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Serializable::ClassMethods
end
module Tapioca::Runtime::Trackers::Autoload
  extend T::Sig
  extend Tapioca::Runtime::Trackers::Tracker
end
module Tapioca::Runtime::Trackers::RequiredAncestor
  extend Tapioca::Runtime::Trackers::Tracker
end
module T
end
module T::Helpers
end
class Tapioca::Runtime::DynamicMixinCompiler
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  include Tapioca::Runtime::Reflection
end
module Tapioca::GemHelper
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class GitAttributes
end
module Tapioca::SorbetHelper
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
module Tapioca::RBIHelper
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  extend Tapioca::RBIHelper
  extend Tapioca::SorbetHelper
  include Tapioca::SorbetHelper
end
module T::Types
end
class T::Types::Simple < T::Types::Base
end
module T::Types::Simple::NamePatch
end
module T::Generic
end
module T::Generic::TypeStoragePatch
end
module T::Types::Simple::GenericPatch
end
module T::Utils
end
module T::Utils::Private
end
module T::Utils::Private::PrivateCoercePatch
end
class Tapioca::TypeVariable < T::Types::TypeVariable
end
class Tapioca::TypeVariableModule < Module
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class Tapioca::TypeVariableModule::Type < T::Enum
end
module T::Types::ProcBindPatch
end
module T::Private
end
module T::Private::Methods
end
module T::Private::Methods::ProcBindPatch
end
module Tapioca::Runtime::GenericTypeRegistry
end
class Tapioca::Runtime::GenericTypeRegistry::GenericType < T::Types::Simple
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
module URI
end
class URI::Source < URI::File
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
module Tapioca::CliHelper
  extend T::Helpers
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
module Tapioca::ConfigHelper
  extend T::Helpers
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class Tapioca::ConfigHelper::ConfigErrorMessagePart < T::Struct
  extend T::Props::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Serializable::ClassMethods
end
class Tapioca::ConfigHelper::ConfigError < T::Struct
  extend T::Props::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Serializable::ClassMethods
end
module Tapioca::RBIFilesHelper
  extend T::Helpers
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
module Tapioca::EnvHelper
  extend T::Helpers
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class Tapioca::RepoIndex
  extend T::Generic
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
module Tapioca::BundlerExt
end
module Tapioca::BundlerExt::AutoRequireHook
  extend T::Helpers
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class Tapioca::Gemfile
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class Tapioca::Gemfile::GemSpec
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  include Tapioca::GemHelper
end
class Tapioca::Executor
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
module Tapioca::Static
end
class Tapioca::Static::SymbolTableParser
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
module Tapioca::Static::SymbolLoader
end
class Tapioca::Static::RequiresCompiler
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
module Tapioca::Loaders
end
class Tapioca::Loaders::Loader
  extend T::Helpers
  extend T::Private::Abstract::Hooks
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  extend Thor::Base::ClassMethods
  extend Thor::Invocation::ClassMethods
  include Tapioca::CliHelper
  include Tapioca::GemHelper
  include Thor::Base
  include Thor::Invocation
  include Thor::Shell
end
class Tapioca::Loaders::Gem < Tapioca::Loaders::Loader
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class Tapioca::Loaders::Dsl < Tapioca::Loaders::Loader
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
module Tapioca::Gem
end
class Tapioca::Gem::Event
  extend T::Helpers
  extend T::Private::Abstract::Hooks
  extend T::Sig
end
class Tapioca::Gem::SymbolFound < Tapioca::Gem::Event
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class Tapioca::Gem::ConstantFound < Tapioca::Gem::Event
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class Tapioca::Gem::ForeignConstantFound < Tapioca::Gem::ConstantFound
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class Tapioca::Gem::NodeAdded < Tapioca::Gem::Event
  extend T::Helpers
  extend T::Private::Abstract::Hooks
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class Tapioca::Gem::ConstNodeAdded < Tapioca::Gem::NodeAdded
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class Tapioca::Gem::ScopeNodeAdded < Tapioca::Gem::NodeAdded
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class Tapioca::Gem::ForeignScopeNodeAdded < Tapioca::Gem::ScopeNodeAdded
end
class Tapioca::Gem::MethodNodeAdded < Tapioca::Gem::NodeAdded
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
module Tapioca::Gem::Listeners
end
class Tapioca::Gem::Listeners::Base
  extend T::Helpers
  extend T::Private::Abstract::Hooks
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class Tapioca::Gem::Listeners::DynamicMixins < Tapioca::Gem::Listeners::Base
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  include Tapioca::Runtime::Reflection
end
class Tapioca::Gem::Listeners::Methods < Tapioca::Gem::Listeners::Base
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  include Tapioca::RBIHelper
  include Tapioca::Runtime::Reflection
end
class Tapioca::Gem::Listeners::Mixins < Tapioca::Gem::Listeners::Base
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  include Tapioca::Runtime::Reflection
end
class Tapioca::Gem::Listeners::RemoveEmptyPayloadScopes < Tapioca::Gem::Listeners::Base
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  include Tapioca::Runtime::Reflection
end
class Tapioca::Gem::Listeners::SorbetEnums < Tapioca::Gem::Listeners::Base
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class Tapioca::Gem::Listeners::SorbetHelpers < Tapioca::Gem::Listeners::Base
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  include Tapioca::Runtime::Reflection
end
class Tapioca::Gem::Listeners::SorbetProps < Tapioca::Gem::Listeners::Base
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  include Tapioca::RBIHelper
end
class Tapioca::Gem::Listeners::SorbetRequiredAncestors < Tapioca::Gem::Listeners::Base
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class Tapioca::Gem::Listeners::SorbetSignatures < Tapioca::Gem::Listeners::Base
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  include Tapioca::RBIHelper
  include Tapioca::Runtime::Reflection
end
class Tapioca::Gem::Listeners::SorbetTypeVariables < Tapioca::Gem::Listeners::Base
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  include Tapioca::Runtime::Reflection
end
class Tapioca::Gem::Listeners::Subconstants < Tapioca::Gem::Listeners::Base
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  include Tapioca::Runtime::Reflection
end
class Tapioca::Gem::Listeners::ForeignConstants < Tapioca::Gem::Listeners::Base
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  include Tapioca::Runtime::Reflection
end
class Tapioca::Gem::Listeners::YardDoc < Tapioca::Gem::Listeners::Base
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class Tapioca::Gem::Listeners::SourceLocation < Tapioca::Gem::Listeners::Base
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class Tapioca::Gem::Pipeline
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  include Tapioca::RBIHelper
  include Tapioca::Runtime::Reflection
end
module RBI
end
class RBI::Tree < RBI::NodeWithComments
  extend T::Sig
end
class RBI::TypedParam < T::Struct
  extend T::Props::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Serializable::ClassMethods
end
class Tapioca::RBIFormatter < RBI::Formatter
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
module Tapioca::Dsl
end
module Tapioca::Dsl::Compilers
end
class Tapioca::Dsl::Pipeline
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class Tapioca::Dsl::Compiler
  extend T::Generic
  extend T::Helpers
  extend T::Private::Abstract::Hooks
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  extend Tapioca::Runtime::Reflection
  include Tapioca::RBIHelper
  include Tapioca::Runtime::Reflection
end
module Tapioca::Dsl::Compiler::ConstantType
end
module Tapioca::Commands
end
class Tapioca::Cli < Thor
  include Tapioca::CliHelper
  include Tapioca::ConfigHelper
  include Tapioca::EnvHelper
end
