AllCops:
  NewCops: enable
  Exclude:
    - 'spec/fixtures/**/*'
  TargetRubyVersion: 3.0
  SuggestExtensions: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/Documentation:
  Enabled: false
