gem:
  # Add your `gem` command parameters here:
  #
  exclude:
   - irb
   - prism
   - psych
   - reline
   - rbi
   - spoom
   - thor
  doc: false
  # workers: 5
dsl:
  # Add your `dsl` command parameters here:
  #
  # exclude:
  # - SomeGeneratorName
  # workers: 5
