# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Bar`.
# Please instead update this file by running `bin/tapioca dsl Bar`.


class Bar
  sig { params(r: ::Float, x: T::Boolean, y: T.nilable(::String), z: T.any(::Integer, T::Boolean)).void }
  def initialize(r: T.unsafe(nil), x:, y: nil, z:); end
end
