# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Bar`.
# Please instead update this file by running `bin/tapioca dsl Bar`.


class Bar
  sig { params(x: T::Boolean, r: ::Float, y: T.nilable(::String), z: T.any(::Integer, T::Boolean)).void }
  def initialize(x:, r: T.unsafe(nil), y: nil, z: T.unsafe(nil)); end
end
