# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Baz`.
# Please instead update this file by running `bin/tapioca dsl Baz`.


class Baz
  sig do
    params(
      a: ::Integer,
      b: ::String,
      c: ::Bar,
      c2: T.nilable(::Foo),
      d: T::Hash[::String, ::String],
      e: T.untyped
    ).void
  end
  def initialize(a:, b:, c:, c2: T.unsafe(nil), d:, e:); end
end
