# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Foo`.
# Please instead update this file by running `bin/tapioca dsl Foo`.


class Foo
  sig { params(r: ::Float).void }
  def initialize(r: T.unsafe(nil)); end
end
