# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: false

module ::Anonymous_Struct_11; end
module ::Anonymous_Struct_7; end
module ::Anonymous_Struct_8; end
module ::Anonymous_Struct_9; end
module T::Private::Abstract::Hooks; end
module T::Private::Methods::MethodHooks; end
module T::Private::Methods::SingletonMethodHooks; end
