# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: false

module Tapioca::Commands::DslGenerate; end
module Tapioca::Compilers::InexactStruct::RBI::KwOptParam; end
module Tapioca::Compilers::InexactStruct::RBI::TypedParam; end
module Tapioca::DEFAULT_GEM_DIR; end
module Tapioca::DEFAULT_RBI_FORMATTER; end
module Tapioca::Dsl::Compiler; end
module Tapioca::TAPIOCA_DIR; end
